.POSIX:
.SUFFIXES:
.SUFFIXES: .cpp
.SUFFIXES: .o

MPICXX = mpicxx
FLAGS = \
-DLAMMPS_BIGBIG \
-DMPICH_SKIP_MPICXX \
-DOMPI_SKIP_MPICXX \

S = \
angle_deprecated.o \
angle_hybrid.o \
angle.o \
angle_write.o \
angle_zero.o \
arg_info.o \
atom_map.o \
atom.o \
atom_vec_atomic.o \
atom_vec_body.o \
atom_vec_charge.o \
atom_vec_ellipsoid.o \
atom_vec_hybrid.o \
atom_vec_line.o \
atom_vec.o \
atom_vec_sphere.o \
atom_vec_tri.o \
balance.o \
body.o \
bond_deprecated.o \
bond_hybrid.o \
bond.o \
bond_zero.o \
change_box.o \
citeme.o \
comm_brick.o \
comm.o \
comm_tiled.o \
compute_aggregate_atom.o \
compute_angle_local.o \
compute_angle.o \
compute_angmom_chunk.o \
compute_bond_local.o \
compute_bond.o \
compute_centro_atom.o \
compute_centroid_stress_atom.o \
compute_chunk_atom.o \
compute_chunk.o \
compute_chunk_spread_atom.o \
compute_cluster_atom.o \
compute_cna_atom.o \
compute_com_chunk.o \
compute_com.o \
compute_coord_atom.o \
compute_deprecated.o \
compute_dihedral_local.o \
compute_dihedral.o \
compute_dipole_chunk.o \
compute_dipole.o \
compute_displace_atom.o \
compute_erotate_rigid.o \
compute_erotate_sphere_atom.o \
compute_erotate_sphere.o \
compute_fragment_atom.o \
compute_global_atom.o \
compute_group_group.o \
compute_gyration_chunk.o \
compute_gyration.o \
compute_heat_flux.o \
compute_improper_local.o \
compute_improper.o \
compute_inertia_chunk.o \
compute_ke_atom.o \
compute_ke.o \
compute_ke_rigid.o \
compute_msd_chunk.o \
compute_msd.o \
compute.o \
compute_omega_chunk.o \
compute_orientorder_atom.o \
compute_pair_local.o \
compute_pair.o \
compute_pe_atom.o \
compute_pe.o \
compute_pressure.o \
compute_property_atom.o \
compute_property_chunk.o \
compute_property_grid.o \
compute_property_local.o \
compute_rdf.o \
compute_reduce_chunk.o \
compute_reduce.o \
compute_reduce_region.o \
compute_rigid_local.o \
compute_slice.o \
compute_stress_atom.o \
compute_temp_chunk.o \
compute_temp_com.o \
compute_temp_deform.o \
compute_temp.o \
compute_temp_partial.o \
compute_temp_profile.o \
compute_temp_ramp.o \
compute_temp_region.o \
compute_temp_sphere.o \
compute_torque_chunk.o \
compute_vacf.o \
compute_vcm_chunk.o \
create_atoms.o \
create_bonds.o \
create_box.o \
delete_atoms.o \
delete_bonds.o \
deprecated.o \
dihedral_deprecated.o \
dihedral_hybrid.o \
dihedral.o \
dihedral_write.o \
dihedral_zero.o \
displace_atoms.o \
domain.o \
dump_atom.o \
dump_cfg.o \
dump_custom.o \
dump_deprecated.o \
dump_grid.o \
dump_grid_vtk.o \
dump_image.o \
dump_local.o \
dump_movie.o \
dump.o \
dump_xyz.o \
error.o \
finish.o \
fix_abf.o \
fix_adapt.o \
fix_addforce.o \
fix_ave_atom.o \
fix_ave_chunk.o \
fix_ave_correlate.o \
fix_aveforce.o \
fix_ave_grid.o \
fix_ave_histo.o \
fix_ave_histo_weight.o \
fix_ave_time.o \
fix_balance.o \
fix_bond_history.o \
fix_box_relax.o \
fix_deform.o \
fix_deposit.o \
fix_deprecated.o \
fix_dt_reset.o \
fix_dummy.o \
fix_efield.o \
fix_ehex.o \
fix_enforce2d.o \
fix_evaporate.o \
fix_external.o \
fix_fileforce.o \
fix_gravity.o \
fix_group.o \
fix_halt.o \
fix_heat.o \
fix_indent.o \
fix_langevin.o \
fix_lineforce.o \
fix_minimize.o \
fix_momentum.o \
fix_move.o \
fix_neigh_history.o \
fix_nh.o \
fix_nh_sphere.o \
fix_nph.o \
fix_nph_sphere.o \
fix_npt.o \
fix_npt_sphere.o \
fix_nve_limit.o \
fix_nve_noforce.o \
fix_nve.o \
fix_nve_sphere.o \
fix_nvt.o \
fix_nvt_sllod.o \
fix_nvt_sphere.o \
fix.o \
fix_pair.o \
fix_planeforce.o \
fix_press_berendsen.o \
fix_print.o \
fix_property_atom.o \
fix_rattle.o \
fix_rbc.o \
fix_read_restart.o \
fix_recenter.o \
fix_respa.o \
fix_restrain.o \
fix_rigid_nh.o \
fix_rigid_nh_small.o \
fix_rigid_nph.o \
fix_rigid_nph_small.o \
fix_rigid_npt.o \
fix_rigid_npt_small.o \
fix_rigid_nve.o \
fix_rigid_nve_small.o \
fix_rigid_nvt.o \
fix_rigid_nvt_small.o \
fix_rigid.o \
fix_rigid_small.o \
fix_sdf_bounceback.o \
fix_sdf_repforce.o \
fix_setforce.o \
fix_shake.o \
fix_spring_chunk.o \
fix_spring.o \
fix_spring_self.o \
fix_store_atom.o \
fix_store_force.o \
fix_store_global.o \
fix_store_local.o \
fix_store_state.o \
fix_temp_berendsen.o \
fix_temp_rescale.o \
fix_thermal_conductivity.o \
fix_update_special_bonds.o \
fix_vector.o \
fix_viscous.o \
fix_wall_harmonic.o \
fix_wall_lj1043.o \
fix_wall_lj126.o \
fix_wall_lj93.o \
fix_wall_morse.o \
fix_wall.o \
fix_wall_reflect.o \
fix_wall_region.o \
fix_wall_table.o \
fmtlib_format.o \
fmtlib_os.o \
force.o \
grid2d.o \
grid3d.o \
group.o \
hashlittle.o \
image.o \
imbalance_group.o \
imbalance_neigh.o \
imbalance.o \
imbalance_store.o \
imbalance_time.o \
imbalance_var.o \
improper_deprecated.o \
improper_hybrid.o \
improper.o \
improper_zero.o \
info.o \
input.o \
integrate.o \
irregular.o \
kspace_deprecated.o \
kspace.o \
label_map.o \
lammps.o \
lattice.o \
library.o \
lmppython.o \
main.o \
math_eigen.o \
math_extra.o \
math_special.o \
memory.o \
min_cg.o \
min_deprecated.o \
min_fire.o \
min_hftn.o \
minimize.o \
min_linesearch.o \
min.o \
min_quickmin.o \
min_sd.o \
modify.o \
molecule.o \
my_page.o \
my_pool_chunk.o \
nbin_multi.o \
nbin.o \
nbin_standard.o \
neighbor.o \
neigh_list.o \
neigh_request.o \
npair_copy.o \
npair_full_bin_atomonly.o \
npair_full_bin_ghost.o \
npair_full_bin.o \
npair_full_multi.o \
npair_full_multi_old.o \
npair_full_nsq_ghost.o \
npair_full_nsq.o \
npair_half_bin_atomonly_newton.o \
npair_half_bin_newtoff_ghost.o \
npair_half_bin_newtoff.o \
npair_half_bin_newton.o \
npair_half_bin_newton_tri.o \
npair_halffull_newtoff.o \
npair_halffull_newtoff_trim.o \
npair_halffull_newton.o \
npair_halffull_newton_trim.o \
npair_half_multi_newtoff.o \
npair_half_multi_newton.o \
npair_half_multi_newton_tri.o \
npair_half_multi_old_newtoff.o \
npair_half_multi_old_newton.o \
npair_half_multi_old_newton_tri.o \
npair_half_nsq_newtoff_ghost.o \
npair_half_nsq_newtoff.o \
npair_half_nsq_newton.o \
npair_half_respa_bin_newtoff.o \
npair_half_respa_bin_newton.o \
npair_half_respa_bin_newton_tri.o \
npair_half_respa_nsq_newtoff.o \
npair_half_respa_nsq_newton.o \
npair_half_size_bin_newtoff.o \
npair_half_size_bin_newton.o \
npair_half_size_bin_newton_tri.o \
npair_half_size_multi_newtoff.o \
npair_half_size_multi_newton.o \
npair_half_size_multi_newton_tri.o \
npair_half_size_multi_old_newtoff.o \
npair_half_size_multi_old_newton.o \
npair_half_size_multi_old_newton_tri.o \
npair_half_size_nsq_newtoff.o \
npair_half_size_nsq_newton.o \
npair.o \
npair_skip.o \
npair_skip_respa.o \
npair_skip_size.o \
npair_skip_size_off2on.o \
npair_skip_size_off2on_oneside.o \
npair_trim.o \
nstencil_full_bin_2d.o \
nstencil_full_bin_3d.o \
nstencil_full_ghost_bin_2d.o \
nstencil_full_ghost_bin_3d.o \
nstencil_full_multi_2d.o \
nstencil_full_multi_3d.o \
nstencil_full_multi_old_2d.o \
nstencil_full_multi_old_3d.o \
nstencil_half_bin_2d.o \
nstencil_half_bin_2d_tri.o \
nstencil_half_bin_3d.o \
nstencil_half_bin_3d_tri.o \
nstencil_half_multi_2d.o \
nstencil_half_multi_2d_tri.o \
nstencil_half_multi_3d.o \
nstencil_half_multi_3d_tri.o \
nstencil_half_multi_old_2d.o \
nstencil_half_multi_old_2d_tri.o \
nstencil_half_multi_old_3d.o \
nstencil_half_multi_old_3d_tri.o \
nstencil.o \
ntopo_angle_all.o \
ntopo_angle_partial.o \
ntopo_angle_template.o \
ntopo_bond_all.o \
ntopo_bond_partial.o \
ntopo_bond_template.o \
ntopo_dihedral_all.o \
ntopo_dihedral_partial.o \
ntopo_dihedral_template.o \
ntopo_improper_all.o \
ntopo_improper_partial.o \
ntopo_improper_template.o \
ntopo.o \
output.o \
pair_born.o \
pair_buck_coul_cut.o \
pair_buck.o \
pair_coul_cut.o \
pair_coul_debye.o \
pair_coul_dsf.o \
pair_coul_wolf.o \
pair_deprecated.o \
pair_dpd_ext.o \
pair_dpd_ext_tstat.o \
pair_dpd.o \
pair_dpd_tstat.o \
pair_hybrid.o \
pair_hybrid_overlay.o \
pair_hybrid_scaled.o \
pair_lj_cut_coul_cut.o \
pair_lj_cut.o \
pair_lj_expand.o \
pair_morse.o \
pair.o \
pair_soft.o \
pair_table.o \
pair_yukawa.o \
pair_zbl.o \
pair_zero.o \
platform.o \
potential_file_reader.o \
procmap.o \
random_mars.o \
random_park.o \
rcb.o \
read_data.o \
read_dump.o \
reader_native.o \
reader.o \
reader_xyz.o \
read_restart.o \
region_block.o \
region_cone.o \
region_cylinder.o \
region_deprecated.o \
region_ellipsoid.o \
region_intersect.o \
region.o \
region_plane.o \
region_prism.o \
region_sphere.o \
region_union.o \
replicate.o \
rerun.o \
reset_atoms_id.o \
reset_atoms_image.o \
reset_atoms_mol.o \
respa.o \
run.o \
set.o \
special.o \
table_file_reader.o \
tabular_function.o \
text_file_reader.o \
thermo.o \
timer.o \
tokenizer.o \
universe.o \
update.o \
utils.o \
variable.o \
velocity.o \
verlet.o \
write_coeff.o \
write_data.o \
write_dump.o \
write_restart.o \

main: $(S:.cpp=.o)
	$(MPICXX) -o main $(S:.cpp=.o) $(LDFLAGS)
.cpp.o:
	$(MPICXX) -o $@ -c $< $(FLAGS) $(CXXFLAGS)
clean:
	-rm main $(S:.cpp=.o)
